//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_kind")]
pub enum PostKind {
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "story")]
    Story,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
