name: deployment

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --workspace

      - name: Upload bin
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: target/release/{nft-adc-platform,system}
          target: ~/axum-pipe-line
